"""changed name for column

Revision ID: a2febaccc885
Revises: 5c56592d7b3a
Create Date: 2024-02-21 11:41:25.159850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2febaccc885'
down_revision = '5c56592d7b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approximate_speed', sa.Integer(), nullable=True))
        batch_op.drop_column('approzimate_speed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approzimate_speed', sa.INTEGER(), nullable=True))
        batch_op.drop_column('approximate_speed')

    # ### end Alembic commands ###
